### ISSUE TITLE
pre releases should not tag to "latest"

### ISSUE THREAD

**Issue by jquense** [AlexKVal/release-script#12]
one more suggestion/feature request :)

right now if you use the preid option it will publish to npm as `latest`, meaning it will be the package shows up on npmjs.com, and what is installed when you `npm install`. Generally I think this is not what folks want as a default for alpha's or beta's. Perhaps we can decide on a default tag (such as "next", or "alpha"/"beta") and tag the release when there is a prelease. It should probably be something it prompts you for when releasing though. 

in terms of technical needs it should just be as simple as running `npm publish --tag [your-tag]`

I could maybe put together a PR if that's helpful.

**Comment by AlexKVal** [comment]
Yeah... I totally agree. It's a `must have` feature.
I'll do it :sparkle:

**Comment by AlexKVal** [comment]
Closed by #14

I've checked it https://github.com/AlexKVal/es6-prototype-proj/releases
I've published it with: `release --preid beta --tag canary`
<img width="870" alt="screen shot 2015-09-15 at 6 55 23 pm" src="https://cloud.githubusercontent.com/assets/847572/9882036/6045ca6c-5bdb-11e5-9fc3-ef214ee7fbdb.png">

Command

``` sh
> npm install es6-prototype-proj@canary
```

will install `"version": "0.0.87-beta.0",`

**Comment by AlexKVal** [comment]
https://github.com/AlexKVal/release-script/releases/tag/v0.3.0 version has been published :tada:
