### ISSUE TITLE
Optional npm run build Step

### ISSUE THREAD

**Issue by mjhasbach** [AlexKVal/release-script#2]
In my use case, I just want release-script to bump / commit / push package.json, author a GitHub release, and run `npm publish`.

If package.json is missing a build script, release-script fails with an error, so I had to manually add a dummy script.

```
"scripts": {
  "build": "echo 0"
}
```

**Comment by AlexKVal** [comment]
This script was designed exactly for projects that needs `build` step. That is the cause why it runs `npm run build`.
But I don't see any hindrance to allow it just skip `build` step if there is no such in `package.json`.
I'll make patch and we can discuss it there :wink:
