### ISSUE TITLE
Prevent trying to push when the remote branch is ahead of the local one

### ISSUE THREAD

**Issue by jquense** [AlexKVal/release-script#28]
One thing that bites me often enough is that I get all the way to the end of trying to release and it fails trying to push the server, because I forgot to pull changes in before attempting to release. It might be nice to fail early for that like it does with "dirty" local repos. that being said I have no idea how to check that with git.

**Comment by AlexKVal** [comment]
I'll try to figure it out.

**Comment by AlexKVal** [comment]
Fixed by https://github.com/AlexKVal/release-script/commit/8a5c227eab3562bb9d6adcba3d27a446e630f588
Updated version has been released: https://github.com/AlexKVal/release-script/releases/tag/v0.5.5
:cherries:
