### ISSUE TITLE
Add --skip-tests Flag

### ISSUE THREAD

**Issue by mjhasbach** [AlexKVal/release-script#29]
I had to deprecate one of my packages today. The tests are failing, preventing release-script from releasing. As a workaround, I am just going to remove `scripts.test` from my `package.json`, but it would be cool if there was a flag to skip tests.

**Comment by AlexKVal** [comment]
@mjhasbach https://github.com/AlexKVal/release-script/releases/tag/v0.5.6 has been released :sparkle: :wink: 
:cherries:

**Comment by mjhasbach** [comment]
Thanks!
