### ISSUE TITLE
Windows-Friendly Build Script

### ISSUE THREAD

**Issue by mjhasbach** [AlexKVal/release-script#36]
In your package.json, you have the following build script:

```
"build": "rm -rf bin && babel src --out-dir bin && chmod +x ./bin/release.js"
```

`rm` and `chmod` don't work on Windows.
- For an `rm` replacement, I recommend [rimraf](https://www.npmjs.com/package/rimraf)
- What is the purpose of using `chmod` on `release.js`?

**Comment by AlexKVal** [comment]
I'm OK with `rimraf`.

I have this line in my shell [zsh/zshrc.symlink#L56-L57](https://github.com/AlexKVal/dotfiles/blob/ab231efe5e1fc0f783c856a86412247e4c289aa3/zsh/zshrc.symlink#L56-L57)

``` sh
# npm
export PATH="./node_modules/.bin:$PATH"
```

It allows me to run locally installed packages straightforward way:

``` sh
> release patch --run
```

Without `chmod` it won't run this way as you see.

Maybe I should add smth like:

``` js
"build-win": "rimraf bin && babel src --out-dir bin"
```

?
Then it would look like: for windows: `npm run build-win` and for unix\* `npm run build`.
It is the simplest way I see. What do you think ?

**Comment by mjhasbach** [comment]
NPM sets the proper permissions (777) on files in the `.bin` directory when running `npm install`. Have a look at [this](https://github.com/npm/npm/blob/580f88a8183375a9c045529f10bf1aaea75f7bdd/lib/build.js#L205) and [this](https://github.com/npm/npm/blob/580f88a8183375a9c045529f10bf1aaea75f7bdd/lib/npm.js#L373). Here's some output from an Ubuntu box:

```
node@hasba:/www/apps/material-qna/node_modules/.bin$ ls -la
total 8
drwxrwxr-x  2 node node 4096 Dec 19 01:31 .
drwxrwxr-x 45 node node 4096 Dec 19 01:31 ..
lrwxrwxrwx  1 node node   19 Oct 18 20:12 jade -> ../jade/bin/jade.js
lrwxrwxrwx  1 node node   24 Dec 18 20:17 nlp -> ../nlp_compromise/cmd.js
lrwxrwxrwx  1 node node   32 Dec 19 01:31 release -> ../release-script/bin/release.js
lrwxrwxrwx  1 node node   21 Dec 18 20:17 uuid -> ../node-uuid/bin/uuid
lrwxrwxrwx  1 node node   25 Dec 18 20:17 webpack -> ../webpack/bin/webpack.js
node@hasba:/www/apps/material-qna/node_modules/.bin$ ./webpack
webpack 1.12.9
...
```

As such, I am having trouble understanding the need to `chmod` during the build process.

Also, `$(npm bin):$PATH` may be a better solution than `./node_modules/.bin:$PATH` for your shell for the reasons mentioned [here](http://stackoverflow.com/questions/9679932/how-to-use-package-installed-locally-in-node-modules).

**Comment by AlexKVal** [comment]
Oh.. I didn't know that `npm install` `chmod`'s all files in `bin`. Nice :+1: Thank you :sparkle: 
Then I could use it.

## 

As for `(npm bin)`. It doesn't work.
I've tried it.
`npm bin` runs only once - when new shell starts - and adds only one _absolute_ path to `PATH`.
So when I change project dir - it doesn't work for me.

E.g. I start new tab in my `Terminal` with this line `export PATH="$(npm bin):$PATH"` in shell scripts.

``` sh
Last login: Thu Jan  7 17:27:50 on ttys005
> alexkval/  
> echo $PATH
/Users/alexkval/node_modules/.bin:/Users/alexkval/.nvm/versions/node/v4.2.3/bin:./bin:/usr/local/bin:/usr/local/sbin:/Users/alexkval/.dotfiles/bin ...etc
```

then I change project dir:

``` sh
> z es6-prototype-proj
es6-prototype-proj/ on master
> release
zsh: command not found: release
```

but as you can see - the script exist:

``` sh
> l node_modules/release-script/bin/release.js 
-rwxr-xr-x  1 alexkval  staff    16K Jan  4 14:01 node_modules/release-script/bin/release.js
```

see ? It doesn't work for me :smile: 

I need _relative_, not absolute `PATH` for each project to `./node_modules/.bin`.

But when I use `export PATH="./node_modules/.bin:$PATH"` in shell scripts it works as it should be:

``` sh
> z es6-prototype-proj
es6-prototype-proj/ on master
> release
Must provide either a version bump type, "preid" or "--only-docs"
Usage: node_modules/.bin/release <version> [--preid <identifier>]
or
... etc
```
