### ISSUE TITLE
how can i only publish bower package and not npm package?

### ISSUE THREAD

**Issue by nanivijay** [AlexKVal/release-script#41]

**Comment by nanivijay** [comment]
how can i skip npm publish package?

**Comment by AlexKVal** [comment]
Hi :)
There is no such option because the main use case is for [React-Bootstrap](https://github.com/react-bootstrap/react-bootstrap) projects and they are rather `npm`-ish than `bower`.

**Comment by nanivijay** [comment]
Thanks for the response. If you can make add this feature it will be useful for me :)

**Comment by AlexKVal** [comment]
It is unlikely now that I will have time for this feature. It is a low priority for me.
Anyway PRs are welcome https://github.com/AlexKVal/release-script/pulls?q=is%3Apr+is%3Aclosed :wink:

**Comment by nanivijay** [comment]
sure. Thanks
