### ISSUE TITLE
When bower.json is present, wrong repository is registered

### ISSUE THREAD

**Issue by tswaters** [AlexKVal/release-script#42]
Trying to get this thing working - seems to work really well.  The bower github repo is populated properly, everything is tagged.

But when it goes to register bower:
https://github.com/AlexKVal/release-script/blob/master/src/release.js#L423

It registers the regular repository, should it not reference `bowerRepo` there?

**Comment by AlexKVal** [comment]
Hey :)
Sorry for lagging with the reply.
I will gladly accept your PR 👍
