### ISSUE TITLE
Bower - branch rather than repo?

### ISSUE THREAD

**Issue by apowers313** [AlexKVal/release-script#6]
I love this project -- it definitely makes it easy to do releases. The one downside is having to create a separate repo for bower.

Would it be possible to push the bower files to a separate branch in the same repo (similar to what [GitHub Pages](https://help.github.com/articles/creating-project-pages-manually/) does for creating docs for a repo)?

**Comment by AlexKVal** [comment]
Hi :smiley: 

It's a nice idea - at the first look. :+1: 

But I've got a question:
how then the versioning should be handled ?

As far as I understand the Bower marks versions by `git tags`
and as far as I know git tags are set for the whole repo.

```
$ git checkout one-branch
$ git tag -l
// and same tags we will get 
$ git checkout another-branch
$ git tag -l
```

With a dedicated bower repo - it is simple - each version has their own tag - pointing to specific commit
https://github.com/react-bootstrap/react-bootstrap-bower/tags
and all works fine.

If we save `Bower package` into e.g. `bower-repo` branch..
then there will be some kind of conflict between `npm` and `bower` tags.

What do you think ?
:cherries:

**Comment by mtscout6** [comment]
I'd agree with @AlexKVal on this one. In the main source repo I like to have the mainline branch tagged with the npm version of the release. Unfortunately Bower has not really been well though out and is too tightly coupled to the git repo, along with other concerns that I don't want to mention here so as to avoid any kind of war between npm and bower. Suffice it to say though the tight coupling of Bower to the github repo is why the separate repo is the best option to go with.
