### ISSUE TITLE
Promise seems to be missing

### ISSUE THREAD

**Issue by jquense** [AlexKVal/release-script#7]
hey!

I was trying this out on a personal repo of mine (on an old version of node) and noticed that `fs-promise` and to some extent `x-changelog` expects Promise to be available. Perhaps this package should declare, `promise` or `bluebird` as a dependency so everything works without me needing to add it as a devDep?

**Comment by jquense** [comment]
Well i looked into it more, and the issue is not here but in the changelog, sorry about that, I sent a fix over here https://github.com/mtscout6/mt-changelog/pull/9

**Comment by AlexKVal** [comment]
Hey. It's nice to hear that you are trying to use it :cherries:

**Comment by jquense** [comment]
its great, I quite enjoy it, switching all my personal stuff over to using it :)
