### ISSUE TITLE
Allow publishing /lib directory directly

### ISSUE THREAD

**Issue by jquense** [AlexKVal/release-script#8]
So there is one pattern I wish I could accomplish with this, that is keeping me from using it for everything. Sometimes I want to actually publish _only_ the `lib` directory as the npm package. I do this for [uncontrollable](https://github.com/jquense/uncontrollable) for instance. That way when you require individual things you can just do `import batch from uncontrollable/batching'` instead of `uncontrollable/lib/batching`.

The general pattern is the same as the current workflow with a change at the end:
1. compile and build files to `/lib`
2. copy `package.json` to `/lib` and copy readme to `/lib`
3. git tag/push/etc
4. `cd ./lib && npm publish`

The one tricky bit is that you really need to trim the normal package.json, removing the scripts and devDependency sections (this is [one way to do it](https://github.com/jquense/uncontrollable/blob/master/create-pkg.js)). It would be great if there was a way to opt into this behavior for projects that it makes sense for, maybe similiarly to how you can opt into the bower repo behavior.

what do you think?

**Comment by AlexKVal** [comment]
I like it.
I'll work on it :sparkle:

**Comment by AlexKVal** [comment]
I see that now `uncontrollable` saves `lib` folder into GitHub.

With `release-script` you won't need to do it and then I presume
it will look slightly different than you described: (change 2 <-> 3 points)
1. compile and build files to `/lib`
2. git tag/push/etc (tags and publish new version to GitHub)

and then will be custom branch if `"altNpmRootFolder": "lib"` set in the `package.json` file
3. copy _customized_ `package.json` and `readme` to `./altNpmRootFolder`
4. cd `./altNpmRootFolder` && npm publish

Am I right ?
(`altNpmRootFolder` maybe you would suggest better name)

**Comment by AlexKVal** [comment]
I'm stopped for now with `altPkgRootFolder` name because `bower` will publish the same content as `npm`
if this `alternative folder` parameter set.

**Comment by jquense** [comment]
Yeah I only push the lib files to github b/c I like being able to require modules installed from github without a build step, but it totally isn't necessary to this, and probably not what most people would do!

`altPkgRootFolder` sounds like a perfectly reasonable name :)

**Comment by AlexKVal** [comment]
I propose to delegate copying of `Readme` and maybe `License` etc files
to `build` script. Because of custom names and custom files.
I will point to this in the docs.

I propose that this custom `altPkgRoot` branch will be handling `package.json` in this way:
copy it as is (with already updated version)
and then just

``` js
delete pkg.scripts
delete pkg.devDependencies
```

What do you think ?

**Comment by jquense** [comment]
that sounds great :+1:

**Comment by jquense** [comment]
O the one caveat. you need to copy the package.json _after_ you bump the version, otherwise it will be one version behind. I aways make that mistake :P

**Comment by AlexKVal** [comment]
Yeah.. It will be exactly `after` the bump of the version.

**Comment by AlexKVal** [comment]
`v0.2.7` has been published.

I've given you push access to my "special" project for this script testing
[es6-prototype-proj](https://github.com/AlexKVal/es6-prototype-proj)
Feel free to play with it and test this new version.

I've checked it already. It does everything as we've discussed
and even removes `lib/` part from the `package.json : main` path :sparkle: 

``` json
"main": "lib/index.js"
```

becomes

``` json
"main": "index.js"
```

just for sure for those who will forget to edit it :wink: 

And o/c you can see all new code at #10 :smile:

**Comment by AlexKVal** [comment]
https://github.com/AlexKVal/es6-prototype-proj/releases/tag/v0.0.87

```
> mkdir tmp && cd tmp
> npm i es6-prototype-proj
> `favorite editor` open node_modules/es6-prototype-proj
```

and you see only the content of `lib/` folder with customized `package.json`
with the new bumped version: `"version": "0.0.87",` :wink:

**Comment by jquense** [comment]
:tada: awesome thanks, I will try it out :)
